const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, 'Frontend', 'env.js');

// Support either a full JSON config string OR individual environment variables
let config = {};

if (process.env.FIREBASE_CONFIG_JSON) {
  try {
    config = JSON.parse(process.env.FIREBASE_CONFIG_JSON);
  } catch (err) {
    console.error('Failed to parse FIREBASE_CONFIG_JSON:', err.message);
  }
} else if (process.env.FIREBASE_API_KEY) {
  config = {
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: process.env.FIREBASE_PROJECT_ID,
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID,
    measurementId: process.env.FIREBASE_MEASUREMENT_ID || ""
  };
}

if (config.apiKey) {
  const fileContent = `// Auto-generated by build script on Vercel\nwindow.__FIREBASE_CONFIG__ = ${JSON.stringify(config, null, 2)};\n`;
  fs.writeFileSync(envPath, fileContent);
  console.log('✅ Generated Frontend/env.js from environment variables.');
} else if (fs.existsSync(envPath)) {
  console.log('ℹ️ Using existing local Frontend/env.js.');
} else {
  console.warn('⚠️ No Firebase environment variables found and Frontend/env.js does not exist.');
  console.warn('Please add FIREBASE_API_KEY or FIREBASE_CONFIG_JSON in your Vercel Project Settings.');
}
